# Source: https://github.com/actions/starter-workflows/blob/main/ci/go.yml
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #v5.0.0
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc #v3.7.0
        with:
          version: latest
          only-new-issues: true

  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: ./go.mod

    - name: Set up gotestfmt
      uses: GoTestTools/gotestfmt-action@v2

    - name: Run tests
      run: |
        set -euo pipefail
        go test -json -v ./... 2>&1 | gotestfmt
